(function(){
 const {testSpec,EXPERT_CONTACT_URL}=window.TypologySpec,texts=window.ResultTexts,host=document.getElementById('app');
 let index=0,answers={};
 const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const answerDefs=[['a2','A','мне заметно ближе A'],['a1','A','мне немного ближе A'],['neutral','↔','оба варианта одинаково подходят / зависит от ситуации'],['b1','B','мне немного ближе B'],['b2','B','мне заметно ближе B']];
 function reset(){index=0;answers={};renderStart();}
 function renderStart(){host.innerHTML=`<section class="start"><div class="eyebrow">24 СИТУАЦИИ · 4 ШКАЛЫ</div><h1>Исследуйте свой<br><em>тип личности</em></h1><p class="lead">Тест даёт гипотезу.<br>Мы проверяем её глубже.</p><p class="intro">Этот тест определяет предварительную типологическую гипотезу по MBTI — на основе четырёх шкал, которые описывают ваши привычные способы воспринимать информацию, принимать решения и взаимодействовать с миром.</p><p class="intro-note"><em>24 ситуационных вопроса займут несколько минут. Выбирайте то, что чаще происходит с вами на самом деле, а не то, каким вам хотелось бы быть.</em></p><div class="privacy"><span class="privacy-mark">↗</span><span>Результат теста — гипотеза, а не психологический диагноз. Он помогает понять, в каком направлении стоит искать ваш тип глубже.</span></div><button class="primary" id="start">Начать тест <span>→</span></button></section>`;document.getElementById('start').onclick=()=>{index=0;answers={};renderQuestion();};}
 function renderQuestion(){const q=testSpec.questions[index];if(!q){renderError();return;}const selected=answers[q.id],progress=index+1;
 const option=([key,marker,label])=>`<button class="answer ${selected===key?'selected':''}" data-answer="${key}" aria-pressed="${selected===key}"><span class="choice">${marker}</span><span class="answer-label">${label}</span></button>`;
 host.innerHTML=`<section class="question"><div class="progress-meta"><span>ВОПРОС ${String(progress).padStart(2,'0')} <i>/ ${testSpec.questions.length}</i></span><span>${Math.round(progress/testSpec.questions.length*100)}%</span></div><div class="progress"><span class="progress-${progress}"></span></div><div class="q-count">${progress} <b>/</b> ${testSpec.questions.length}</div><h2>${esc(q.prompt)}</h2><div class="pair"><div><span>A</span><p>${esc(q.a)}</p></div><div><span>B</span><p>${esc(q.b)}</p></div></div><p class="choose-hint">Что чаще происходит с вами в последнее время?</p><div class="answers">${answerDefs.map(option).join('')}</div><button class="skip-answer ${selected==='skip'?'selected':''}" data-answer="skip" aria-pressed="${selected==='skip'}">Не могу ответить <span>Оставить эту ситуацию без оценки</span></button><div class="question-foot"><button class="back" id="back" ${index===0?'disabled':''}>← Назад</button><span>Выбор можно изменить, вернувшись назад</span></div></section>`;
 host.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{answers[q.id]=b.dataset.answer;if(index<testSpec.questions.length-1){index++;renderQuestion();}else{const result=window.TypologyScoring.calculateResult(answers,testSpec);result.ok?renderResult(result):renderError();}});
 document.getElementById('back').onclick=()=>{if(index>0){index--;renderQuestion();}};
 }
 function renderResult(r){
  const dims=testSpec.dimensionPriority, unresolved=r.unresolvedDimensions, incomplete=r.unscoredDimensions, alternatives=r.alternativeHypotheses;
  const axisRows=dims.map(d=>{const x=r.dimensions[d],direction=x.direction?texts.poleNames[x.direction]:x.complete?'Пока не различена':'Недостаточно ответов по этой оси';const flag=x.contextConflict?`<p class="context-flag">Контекстно неоднозначна</p>`:'';const marker=x.direction===testSpec.dimensions[d].positive?'axis-pos':x.direction===testSpec.dimensions[d].negative?'axis-neg':'axis-mid';const visualScore=x.complete?Math.max(-12,Math.min(12,x.score)):0;const scoreClass=`score-marker-${visualScore<0?'n'+Math.abs(visualScore):visualScore}`;return `<div class="dimension ${marker}"><div class="dimension-top"><span>${texts.axisNames[d]}</span><span>${x.complete?(x.direction?'Есть направление':'Близко к середине'):'Недостаточно ответов'}</span></div><div class="dim-poles"><b class="${x.direction===testSpec.dimensions[d].positive?'on':''}">${testSpec.dimensions[d].positive}</b><span class="dim-line"><i class="${scoreClass}"></i></span><b class="${x.direction===testSpec.dimensions[d].negative?'on':''}">${testSpec.dimensions[d].negative}</b></div><p>${direction}</p>${flag}</div>`;}).join('');
  const codeMarkup=code=>`<span class="code-letters">${dims.map((d,i)=>`<span class="${r.contextAmbiguousDimensions.includes(d)?'context-code-letter':''}">${esc(code[i])}${r.contextAmbiguousDimensions.includes(d)?'<sup>*</sup>':''}</span>`).join('<i>·</i>')}</span>`;
  let hypothesis='';
  if(r.primaryHypothesis){hypothesis=`<div class="type-code">${codeMarkup(r.primaryHypothesis)}</div><p class="type-label">Предварительная гипотеза по ответам этого прохождения${r.contextAmbiguousDimensions.length?'; * отмечает контекстно неоднозначную ось':''}</p>`;}
  else if(r.hypothesisStatus==='one_unresolved'){hypothesis=`<div class="type-code">${codeMarkup(r.profilePattern)}</div><p class="type-label">Ось X не различилась; варианты равноправны</p><div class="family-codes">${alternatives.map(x=>`<span>${codeMarkup(x)}</span>`).join('')}</div>`;}
  else if(r.hypothesisStatus==='two_unresolved'){hypothesis=`<div class="type-code">${codeMarkup(r.profilePattern)}</div><p class="type-label">Две оси пока не различились; возможные сочетания не ранжируются</p><div class="family-codes">${alternatives.map(x=>`<span>${codeMarkup(x)}</span>`).join('')}</div>`;}
  else if(r.hypothesisStatus==='broad_profile'){hypothesis=`<div class="type-code">— — — —</div><p class="type-label">Данных этого прохождения недостаточно для узкой четырёхбуквенной гипотезы</p>`;}
  else{hypothesis=`<div class="type-code">${codeMarkup(r.profilePattern)}</div><p class="type-label">Полный код не показывается: по отмеченным осям недостаточно ответов</p>`;}
  const altHtml=r.primaryHypothesis&&alternatives.length?`<div class="note"><span class="note-label">РАВНОВОЗМОЖНЫЕ БЛИЖАЙШИЕ АЛЬТЕРНАТИВЫ</span><div class="family-codes">${alternatives.map(x=>`<span>${codeMarkup(x)}</span>`).join('')}</div><p>Каждый вариант отличается от основной гипотезы по одной из осей с минимальным различием. При равенстве осей варианты показаны без ранжирования. Это не рейтинг и не вероятность.</p></div>`:'';
  const support=r.supportDimensions.map(d=>{const pole=r.dimensions[d].direction,qs=testSpec.questions.filter(q=>q.dimension===d&&answers[q.id]&&answers[q.id]!=='skip').filter(q=>{const k=answers[q.id];return pole===testSpec.dimensions[d].positive?k.startsWith('a'):k.startsWith('b');});const choices=qs.map(q=>answers[q.id][0]==='a'?q.a:q.b);return `<div class="support-item"><b>${texts.axisNames[d]}</b><p>В этом прохождении направление поддерживали ответы: ${choices.slice(0,2).map(x=>`«${esc(x)}»`).join('; ')}.</p></div>`;}).join('');
  const contextHtml=r.contextAmbiguousDimensions.length?`<div class="note"><span class="note-label">КОНТЕКСТНО НЕОДНОЗНАЧНЫЕ ОСИ</span><p>${r.contextAmbiguousDimensions.map(d=>texts.axisNames[d]).join('; ')}.</p><p>${texts.context}</p></div>`:'';
  const missingHtml=incomplete.length?`<div class="note"><span class="note-label">НЕПОЛНОЕ ПРОХОЖДЕНИЕ</span><p>Недостаточно ответов по осям: ${incomplete.map(d=>texts.axisNames[d]).join('; ')}. По ним направление не рассчитывается; полный код не формируется.</p></div>`:'';
  const clarity=texts.clarity[r.clarity];
  host.innerHTML=`<section class="result"><div class="eyebrow">РЕЗУЛЬТАТ · ВЕРСИЯ ${esc(r.testVersion)}</div><h1>Профиль ответов,<br><em>а не ярлык.</em></h1><div class="hypothesis">${hypothesis}</div><div class="confidence"><span class="confidence-dot ${r.clarity}"></span><div><b>${clarity.label}</b><p>${clarity.text}</p><p class="clarity-caption"><em>Выраженность сигнала отражает определённость профиля в этом прохождении, а не вероятность правильности определения типа</em></p></div></div>${altHtml}<section class="result-section"><div class="section-kicker">ОСЕВЫЕ СИГНАЛЫ</div><div class="dimensions">${axisRows}</div></section>${contextHtml}${missingHtml}<section class="result-section support"><div class="section-kicker">ЧТО ПОДДЕРЖИВАЕТ ПРОФИЛЬ</div>${support||'<p>В этом прохождении недостаточно ответов, чтобы выделить поддерживающие кластеры.</p>'}</section><section class="limitation"><div class="section-kicker">КАК ЧИТАТЬ РЕЗУЛЬТАТ</div><p>${texts.limitation}</p></section><section class="expert"><p>${texts.cta}</p><a class="primary expert-link" href="${esc(EXPERT_CONTACT_URL)}" target="_blank" rel="noopener noreferrer">Напишите нам, чтобы обсудить результаты с экспертом <span>↗</span></a></section><button class="restart" id="restart">Пройти тест заново</button></section>`;
  document.getElementById('restart').onclick=reset;
 }
 function renderError(){host.innerHTML=`<section class="error"><div class="error-mark">!</div><h1>Результат не сложился.</h1><p>Не удалось корректно рассчитать результат. Пройдите тест ещё раз.</p><button class="primary" id="retry">Пройти заново <span>↻</span></button></section>`;document.getElementById('retry').onclick=reset;}
 renderStart();
})();
