const assert=require('node:assert/strict');
const {testSpec}=require('../js/test-spec.js');const {calculateResult}=require('../js/scoring.js');
const dims=testSpec.dimensionPriority,opts=['a2','a1','neutral','b1','b2'];
const results=[];
function run(a){const r=calculateResult(a,testSpec);assert.equal(r.ok,true,JSON.stringify(r));return r;}
function ansFromValues(values){const a={};for(const q of testSpec.questions){const x=values[q.dimension]?.[q.sequence-1]??2;a[q.id]=x===0?'neutral':x>0?'a'+x:'b'+(-x);}return a;}
function findValues(target){function rec(n,left,out){if(n===0)return left===0?out:null;for(const v of [2,1,0,-1,-2]){const r=rec(n-1,left-v,[...out,v]);if(r)return r;}return null;}return rec(6,target,[]);}
function targetAnswers(target){const values={};for(const d of dims){values[d]=findValues(target[d]);assert.ok(values[d],`not representable ${d}:${target[d]}`);}return ansFromValues(values);}
function scores(r){return dims.map(d=>r.dimensions[d].score);}
function check(name,fn){fn();results.push(name);}
check('spec is 24 mixed questions, 6 per axis, split into two triples',()=>{assert.equal(testSpec.questions.length,24);for(const d of dims){const q=testSpec.questions.filter(x=>x.dimension===d);assert.equal(q.length,6);assert.equal(q.filter(x=>x.half===1).length,3);assert.equal(q.filter(x=>x.half===2).length,3);}assert.notDeepEqual(testSpec.questions.map(q=>q.dimension),['EI','EI','EI','EI','EI','EI','SN']);});
check('A polarity uses poleA and maps all +12 to ESTJ',()=>{const a=Object.fromEntries(testSpec.questions.map(q=>[q.id,'a2']));const r=run(a);assert.deepEqual(scores(r),[12,12,12,12]);assert.equal(r.primaryHypothesis,'ESTJ');});
check('all B noticeably closer gives -12 and INFP',()=>{const a=Object.fromEntries(testSpec.questions.map(q=>[q.id,'b2']));const r=run(a);assert.deepEqual(scores(r),[-12,-12,-12,-12]);assert.equal(r.primaryHypothesis,'INFP');});
check('neutral across all items is zero, unresolved, low signal, no type',()=>{const a=Object.fromEntries(testSpec.questions.map(q=>[q.id,'neutral']));const r=run(a);assert.deepEqual(scores(r),[0,0,0,0]);assert.equal(r.profilePattern,'XXXX');assert.equal(r.primaryHypothesis,null);assert.equal(r.hypothesisStatus,'broad_profile');assert.equal(r.clarity,'low');});
check('score +3/-3 resolves; +2/-2 stays X',()=>{for(const score of [3,-3]){const r=run(targetAnswers({EI:score,SN:6,TF:6,JP:6}));assert.equal(r.dimensions.EI.direction,score>0?'E':'I');}for(const score of [2,-2]){const r=run(targetAnswers({EI:score,SN:6,TF:6,JP:6}));assert.equal(r.dimensions.EI.direction,null);assert.equal(r.hypothesisStatus,'one_unresolved');assert.ok(r.profilePattern.includes('X'));}});
check('complete directed profile shows nearest alternative',()=>{const r=run(targetAnswers({EI:3,SN:6,TF:-8,JP:-7}));assert.equal(r.primaryHypothesis,'ESFP');assert.deepEqual(r.alternativeHypotheses,['ISFP']);assert.equal(r.clarity,'medium');assert.deepEqual(r.contextAmbiguousDimensions,['EI']);});
check('tied weakest axes produce every equal alternative without ranking',()=>{const r=run(targetAnswers({EI:3,SN:-3,TF:8,JP:-8}));assert.equal(r.primaryHypothesis,'ENTP');assert.equal(r.alternativeHypotheses.length,2);assert.deepEqual(r.alternativeHypotheses,['INTP','ESTP']);});
check('one unresolved axis shows X pattern and two equal variants',()=>{const r=run(targetAnswers({EI:0,SN:-6,TF:6,JP:-6}));assert.equal(r.profilePattern,'X N T P'.replaceAll(' ',''));assert.equal(r.primaryHypothesis,null);assert.deepEqual(r.alternativeHypotheses,['INTP','ENTP']);assert.equal(r.hypothesisStatus,'one_unresolved');});
check('two unresolved axes show all four unranked combinations',()=>{const r=run(targetAnswers({EI:0,SN:-6,TF:6,JP:0}));assert.equal(r.hypothesisStatus,'two_unresolved');assert.equal(r.alternativeHypotheses.length,4);assert.equal(r.primaryHypothesis,null);assert.ok(r.alternativeHypotheses.every(x=>x.length===4));});
check('three unresolved axes do not yield a four-letter type',()=>{const r=run(targetAnswers({EI:0,SN:0,TF:3,JP:0}));assert.equal(r.hypothesisStatus,'broad_profile');assert.equal(r.primaryHypothesis,null);assert.equal(r.profilePattern,'XXTX');});
check('context conflict keeps scores, marks axis, and lowers clarity',()=>{const a=Object.fromEntries(testSpec.questions.map(q=>[q.id,'a2']));for(const q of testSpec.questions.filter(q=>q.dimension==='EI'&&q.half===2))a[q.id]='b2';const r=run(a);assert.equal(r.dimensions.EI.score,0);assert.equal(r.dimensions.EI.h1,6);assert.equal(r.dimensions.EI.h2,-6);assert.equal(r.dimensions.EI.contextConflict,true);assert.deepEqual(r.contextAmbiguousDimensions,['EI']);assert.equal(r.clarity,'medium');});
check('two context-conflict axes downgrade clarity to low',()=>{const a=Object.fromEntries(testSpec.questions.map(q=>[q.id,'a2']));for(const d of ['EI','SN'])for(const q of testSpec.questions.filter(q=>q.dimension===d&&q.half===2))a[q.id]='b2';const r=run(a);assert.equal(r.contextAmbiguousDimensions.length,2);assert.equal(r.clarity,'low');});
check('an unscored axis suppresses full type and clarity assessment',()=>{const a=Object.fromEntries(testSpec.questions.map(q=>[q.id,'a2']));a[testSpec.questions.find(q=>q.dimension==='EI').id]='skip';const r=run(a);assert.equal(r.complete,false);assert.equal(r.dimensions.EI.status,'unscored');assert.equal(r.dimensions.EI.direction,null);assert.equal(r.primaryHypothesis,null);assert.equal(r.clarity,'not_assessed');});
check('missing question suppresses its axis; other complete axes remain available',()=>{const a=Object.fromEntries(testSpec.questions.map(q=>[q.id,'a2']));delete a[testSpec.questions.find(q=>q.dimension==='JP').id];const r=run(a);assert.equal(r.dimensions.JP.status,'unscored');assert.equal(r.dimensions.JP.direction,null);assert.equal(r.dimensions.EI.direction,'E');assert.equal(r.primaryHypothesis,null);});
check('mixed +2,+1,+1,-1,-1,-2 aggregates to zero',()=>{const a=Object.fromEntries(testSpec.questions.map(q=>[q.id,'a1']));const qs=testSpec.questions.filter(q=>q.dimension==='EI').sort((x,y)=>x.sequence-y.sequence);[2,1,1,-1,-1,-2].forEach((v,i)=>a[qs[i].id]=v===0?'neutral':v>0?'a'+v:'b'+(-v));assert.equal(run(a).dimensions.EI.score,0);});
check('reverse every answered pole inverts each axis score',()=>{const a=targetAnswers({EI:6,SN:-3,TF:8,JP:-7}),inv={};for(const q of testSpec.questions){const k=a[q.id];inv[q.id]=k[0]==='a'?'b'+k[1]:k[0]==='b'?'a'+k[1]:k;}assert.deepEqual(scores(run(inv)),scores(run(a)).map(x=>-x));});
check('swapping A/B together with the question key preserves scores',()=>{const a=targetAnswers({EI:6,SN:-3,TF:8,JP:-7}),spec=JSON.parse(JSON.stringify(testSpec)),q=spec.questions[0],originalPole=q.poleA,dimension=spec.dimensions[q.dimension];[q.a,q.b]=[q.b,q.a];q.poleA=originalPole===dimension.positive?dimension.negative:dimension.positive;const swapped={...a,[q.id]:a[q.id]==='neutral'?'neutral':a[q.id]==='skip'?'skip':(a[q.id][0]==='a'?'b':'a')+a[q.id][1]};assert.deepEqual(scores(calculateResult(swapped,spec)),scores(run(a)));});
check('answer object order does not affect calculation',()=>{const a=targetAnswers({EI:6,SN:-3,TF:8,JP:-7});assert.deepEqual(scores(run(Object.fromEntries(Object.entries(a).reverse()))),scores(run(a)));});
check('input validation covers malformed, unknown, invalid, and unapproved rules',()=>{assert.equal(calculateResult(null,testSpec).error,'INVALID_INPUT');const a=targetAnswers({EI:6,SN:6,TF:6,JP:6});assert.equal(calculateResult({...a,other:'a1'},testSpec).error,'UNKNOWN_QUESTION');assert.equal(calculateResult({...a,[testSpec.questions[0].id]:'bad'},testSpec).error,'INVALID_ANSWER');const bad=JSON.parse(JSON.stringify(testSpec));bad.rules.axis.positiveMin=4;assert.equal(calculateResult(a,bad).error,'RULES_NOT_APPROVED');});
check('exhaustive 5^6 enumeration of one axis: 15,625 combinations',()=>{let nChecked=0;const total=5**6;for(let n=0;n<total;n++){let x=n;const a=Object.fromEntries(testSpec.questions.map(q=>[q.id,'a1']));let expected=0;const qs=testSpec.questions.filter(q=>q.dimension==='EI');for(const q of qs){const opt=opts[x%5];x=Math.floor(x/5);a[q.id]=opt;const v=testSpec.answerOptions[opt];expected+=v.side==='A'?v.degree:v.side==='B'?-v.degree:0;}const r=run(a),d=r.dimensions.EI;assert.equal(d.score,expected);assert.ok(Number.isInteger(d.score)&&d.score>=-12&&d.score<=12);assert.equal(d.direction,d.score>=3?'E':d.score<=-3?'I':null);assert.equal(d.contextConflict,((d.h1>=2&&d.h2<=-2)||(d.h1<=-2&&d.h2>=2)));nChecked++;}assert.equal(nChecked,15625);});
console.log(JSON.stringify({ok:true,exhaustiveChecked:15625,cases:results},null,2));
